export default {
  Date: '日期',
  Money: '当日平仓收益',
  TotalMoney: '当前日期的累计收益',
  TotalSelfMoney: '自主累计收益',
  TotalFollowMoney: '跟随累计收益',
  TotalStandardlots: '总手数',
  TotalSelfStandardlots: '自主手数',
  TotalFollowStandardlots: '跟随手数',
  TotalPips: '总点数',
  TotalSelfPips: '自主点数',
  TotalFollowPips: '跟随点数',
  FollowMoney: '跟随收益',
  Score: '交易能力值',
  ROI: '收益率',
  MaxRetracement: '最大回撤',
  Weeks: '交易周期',
  DealAmount: '交易笔数',
  Equity: '账户净值',
  ExpSymbol: '擅长品种',
  Subscribers: '订阅人数',
};
